### ISSUE TITLE
Gamemode Idea

### ISSUE THREAD

**Issue by SavaLava9** [KARPED1EM/TownOfNext#133]
Cops And Robbers.

Settings:
Randomize Prison Location: Options Yes or No
if No:
No Options
if Yes:
Options
Skeld
(Insert Location) Toggle On or Off
Mira
(Insert Location) Toggle On or Off
Polus
(Insert Location) Toggle On or Off
Airship
(Insert Location) Toggle On or Off

Cop Cooldown: 1s 5s 10s 20s 30s 50s 100s

(add more settings if you like)

How it works

Impostor Role: Cop

Crewmate Role: Criminal

The cops chase the criminal and click kill when near them, when caught prisoners will be set to a prison (all locations if randomize prison location is off) and the criminal is a prisoner. a criminal finds them and then touches them then the prisoner turns back into a criminal, they have 100seconds before the game ends and criminals wins. If the polices catch all the prisoners they win.

**Comment by KARPED1EM** [comment]
sorry we don't plan to add any game mod
