### ISSUE TITLE
TONX is reported as a Trojan by anti-virus software

### ISSUE THREAD

**Issue by GD825** [KARPED1EM/TownOfNext#159]
windows defender is auto deleting the dll and reporting it as a trojan.. any idea why it thinks so?

**Comment by KARPED1EM** [comment]
### I don't know much about anti-virus, here are my guesses:

---

1. Trojans often obtain some information from attackers by connecting to the network. TONX will obtain real-time announcements and new version information through the Internet. Such operations may be considered Trojan behavior by anti-virus software. Here are the relevant code locations:

- https://github.com/KARPED1EM/TownOfNext/blob/TONX/TONX/Modules/ModUpdater.cs#L91
- https://github.com/KARPED1EM/TownOfNext/blob/TONX/TONX/Modules/ModUpdater.cs#L155

2. Trojans often transmit part of the victim’s computer information by connecting to the attacker’s server. TONX’s anti-cheating system, EAC, attempts to connect to TONX’s servers and report the cheater’s information. And if you enable the option "Request TONX-Chan to share your lobby number to Discord", then TONX-Chan will also try to send your lobby code to TONX's server. Such operations may also be considered Trojan behavior by anti-virus software. Here are the relevant code locations:

- https://github.com/KARPED1EM/TownOfNext/blob/TONX/TONX/Modules/Cloud.cs#L111

---

### The second part above has been abandoned in TONX, and the TONX server has been completely shut down. Therefore, TONX will only check the new version information at startup and will not upload any of your information to our server. Please rest assured.

**Comment by GD825** [comment]
its wierd b/c  it doesnt report it as one for myself, but for one of the people that hosts , with the same antivirus setup as me,  her system reports it as a trojan and auto deletes it from the download, or refuses to let her download  just the dll. but me and and another player with the same anti virus program as her, doesnt have that issue at all

**Comment by GD825** [comment]
thats the thing tho, she cant even load up the mod b/c it deletes the dll before it even makes it to the folder location of the mod, and refuses to let her download the dll solo, so she cant even get the dll onto her system

**Comment by KARPED1EM** [comment]
Cloud related code has been disabled in dev build
If this issue is not resolved after released, please reopen this issue
