### ISSUE TITLE
[Bug] f2沒有用

### ISSUE THREAD

**Issue by FlyFlyTurtle** [KARPED1EM/TownOfNext#160]
**描述错误**
f2看不到附加職業的內容

**如何重现**
重现这个错误的步骤:
1按f2沒有用(就這麼簡單)

**截图**
如果需要，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/KARPED1EM/TownOfNext/assets/142894763/626cbc89-29c5-4d3c-82b6-a6704e3392bb)

**日志**
如果可以，尽可能上传日志文件以更快解决这个问题。[如何获取日志文件](https://tonx.cc/zh/docs/FAQ.html#如何得到日志文件)
[TONX-v3.0.0-2023-11-16_22.02.54.log](https://github.com/KARPED1EM/TownOfNext/files/13378432/TONX-v3.0.0-2023-11-16_22.02.54.log)

**Comment by FlyFlyTurtle** [comment]
btw f1有用的

**Comment by KARPED1EM** [comment]
遊戲內快捷鍵職業介紹查看頁面有計畫重做，f2確實被暫時刪除了。 不過謝謝你的回饋tho。

**Comment by KARPED1EM** [comment]
已經在Dev版本修復
