### ISSUE TITLE
[Bug] Anti-black screen continues to work when not needed

### ISSUE THREAD

**Issue by DopzyGamer** [KARPED1EM/TownOfNext#161]
BUG

in my game i start a match, and the ejection screen never appears because it has an anti black screen with 1 impostor, and i put 3 impostors, i don't know what's going on but it's a bug

**Comment by KARPED1EM** [comment]
Are there actually three imp in the game?
This problem may also occur if there are too few people in your game

**Comment by DopzyGamer** [comment]
there are 3 imposters, and it keeps giving me this

**Comment by DopzyGamer** [comment]
![image](https://github.com/KARPED1EM/TownOfNext/assets/71271091/6c415e15-c113-4909-a609-0c882adce0a7)

**Comment by KARPED1EM** [comment]
kk i see, btw do you have a log file?

**Comment by DopzyGamer** [comment]
I don't know where the logs folder is

**Comment by KARPED1EM** [comment]
heres how to get log
https://tonx.cc/docs/FAQ.html#how-to-get-the-log-file

**Comment by DopzyGamer** [comment]
[Uploading TONX-v3.0.0-2023-11-16_18.21.18.log…]()

**Comment by DopzyGamer** [comment]
[TONX-v3.0.0-2023-11-16_18.21.18.log](https://github.com/KARPED1EM/TownOfNext/files/13383905/TONX-v3.0.0-2023-11-16_18.21.18.log)

**Comment by KARPED1EM** [comment]
This is b/c there are roles with independent team such as Jackals, Succubi, and Pelican in the game, which will trigger this mechanism. This is a prompt description mistake and will be corrected in the next version
