### ISSUE TITLE
[Bug] switch to vanika 之後做不了任何事

### ISSUE THREAD

**Issue by FlyFlyTurtle** [KARPED1EM/TownOfNext#163]
**描述错误**
在模組設定按switch to vanila之後就甚麼都做不了(只可以開shop,inventory)

**如何重现**
重现这个错误的步骤:
1. 前往 'mod settings...'
2. 点击 '...switch to vanila.'

**截图**
如果需要，请添加屏幕截图以帮助解释您的问题。

**日志**
如果可以，尽可能上传日志文件以更快解决这个问题。[如何获取日志文件](https://tonx.cc/zh/docs/FAQ.html#如何得到日志文件)

**Comment by NetherDragonTw** [comment]
wdym?
切換至原版之後就等於卸載了mod
不是有警告說得清清楚楚嗎
