### ISSUE TITLE
[Bug] Low fps

### ISSUE THREAD

**Issue by NikoCat233** [KARPED1EM/TownOfNext#165]
在公开游戏host
当玩家数比较多的时候游戏会嘎嘎掉帧
在debug日志里面看不到有用信息
我是拿debug自编译的，加了protectplayer，别的一点没动

**Comment by NikoCat233** [comment]
我再去开个房弄个日志

**Comment by NikoCat233** [comment]
怪事 人一少就非常稳定(9个人左右)
感觉是哪个职业的问题

**Comment by NikoCat233** [comment]
[TONX-v3.0.0-2023-11-18_15.35.45.log](https://github.com/KARPED1EM/TownOfNext/files/13399468/TONX-v3.0.0-2023-11-18_15.35.45.log)
Hudmanager里面有个refer to null错误
日志看不出来是什么问题，感觉这个是罪魁祸首

**Comment by NikoCat233** [comment]
房主开局存活的情况下不发生hudmanager refer to null报错
但是依然掉帧++

SyncSettings里面有个ghostdotasks的会产生unity报错，不会被记录到tohe日志里面
我屏幕上控制台一直在刷
不管是不是这个导致的，都可以参考tohehanced的方法排除ghostdotasks 这的确可以显著提高性能

**Comment by NikoCat233** [comment]
[TONX-v3.0.0-2023-11-18_15.45.50.log](https://github.com/KARPED1EM/TownOfNext/files/13399501/TONX-v3.0.0-2023-11-18_15.45.50.log)
大厅里面很流畅，一进游戏就卡死

**Comment by NikoCat233** [comment]
<img width="608" alt="image" src="https://github.com/KARPED1EM/TownOfNext/assets/139348239/3384a9ec-917b-43d9-b6f6-37829e0ecf11">
/r貌似也有点毛病

**Comment by NikoCat233** [comment]
/l /win有毛病
只能显示击杀记录

**Comment by NikoCat233** [comment]
The awesome lag is mainly caused by Roletext in onfixedupdate
<img width="331" alt="image" src="https://github.com/KARPED1EM/TownOfNext/assets/139348239/594b3286-aa72-459c-9fa0-5c618befdf19">

Disable this and my game fps ++165

**Comment by KARPED1EM** [comment]
你人还怪好的嘞，帮我测好了

**Comment by KARPED1EM** [comment]
顺带修了给我发个Pr吧

![745e86cbe8a3654b5224484e0665fc4f](https://github.com/KARPED1EM/TownOfNext/assets/89320463/496c3569-62b5-4afa-aeb6-d5d183a092dd)

**Comment by NikoCat233** [comment]
唯一的问题是我不会修

**Comment by KARPED1EM** [comment]
无所谓，反正我打算重做游戏内职业介绍画面

**Comment by NikoCat233** [comment]
酷炫

**Comment by NikoCat233** [comment]
等我再学一年C再来写界面

**Comment by NikoCat233** [comment]
公开界面点搜索游戏卡死崩溃是已知bug吗？

**Comment by KARPED1EM** [comment]
> 公开界面点搜索游戏卡死崩溃是已知bug吗？

没issue就不是已知

**Comment by NikoCat233** [comment]
不确定是不是bug
我移除+25协议后点一次崩一次

**Comment by KARPED1EM** [comment]
> 等我再学一年C再来写界面

不至于，我也才学半年，估摸这玩意你看看就会了，不难

**Comment by KARPED1EM** [comment]
> +25协议

+25协议是什么

**Comment by NikoCat233** [comment]
<img width="442" alt="image" src="https://github.com/KARPED1EM/TownOfNext/assets/139348239/f253f2c8-6e0d-4781-8d56-bb52335fa8b8">
树懒粑粑提供的超级版本协议

**Comment by NikoCat233** [comment]
这个协议改版本解除反作弊 但是锁房
所以我把他弄了
