### ISSUE TITLE
[Bug] 網紅沒有閃爍

### ISSUE THREAD

**Issue by FlyFlyTurtle** [KARPED1EM/TownOfNext#169]
**描述错误**
celebrity(網紅)沒有閃爍(即使設定開啟了內鬼可以知道網紅死了)

**如何重现**
重现这个错误的步骤:
1. 前往 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 出现错误

**截图**
如果需要，请添加屏幕截图以帮助解释您的问题。

**日志**
如果可以，尽可能上传日志文件以更快解决这个问题。[如何获取日志文件](https://tonx.cc/zh/docs/FAQ.html#如何得到日志文件)

**Comment by FlyFlyTurtle** [comment]
我嘗試不同的殺法,內鬼職業都沒用
![image](https://github.com/KARPED1EM/TownOfNext/assets/142894763/8b143612-38bb-4d8d-8c7a-45825748e3bf)

**Comment by KARPED1EM** [comment]
已在dev版本修復
