### ISSUE TITLE
[Bug] rapirman不可以跳地道

### ISSUE THREAD

**Issue by FlyFlyTurtle** [KARPED1EM/TownOfNext#170]
**描述错误**
維修工(對吧)不可以跳地道

**如何重现**
重现这个错误的步骤:
1. 前往 '...'
2. 点击 '....'
3. 滑动至 '....'
4. 出现错误

**截图**
![image](https://github.com/KARPED1EM/TownOfNext/assets/142894763/88ee8920-87db-474a-b6e2-272817c1d57b)
base role 是船員,怎麼用地道呢

**日志**
如果可以，尽可能上传日志文件以更快解决这个问题。[如何获取日志文件](https://tonx.cc/zh/docs/FAQ.html#如何得到日志文件)

**Comment by KARPED1EM** [comment]
已在dev版本修復
