### ISSUE TITLE
[Question] 关于变形者

### ISSUE THREAD

**Issue by Slok7565** [KARPED1EM/TownOfNext#176]
**描述问题**
变形者作为中立时的变形按钮让人爆炸

**附加内容**

![image](https://github.com/KARPED1EM/TownOfNext/assets/137697902/726256bc-94e9-4f18-8cd0-71d653af311e)

**Comment by KARPED1EM** [comment]
变形者怎么作为中立的

**Comment by Slok7565** [comment]
整一个中立的时候想拿变形按钮作为倒计时

**Comment by Slok7565** [comment]
内鬼船员什么的都能作为中立变形者理应也能吧(?)

**Comment by KARPED1EM** [comment]
没听懂

**Comment by Slok7565** [comment]
就是说我想要一个中立的RoleType是变形者，但是变形按钮有问题

**Comment by NikoCat233** [comment]
TOHE那边研究过，不知道为什么你给mod side变形角色，技能按钮就是非法的

**Comment by Slok7565** [comment]
> TOHE那边研究过，不知道为什么你给非内鬼mod side变形角色，技能按钮就是非法的

可能是本家干的(?)
