### ISSUE TITLE
[Bug] 老兵，掷雷兵等带有“技能持续时间”的职业技能持续时间翻倍

### ISSUE THREAD

**Issue by Slok7565** [KARPED1EM/TownOfNext#177]
**描述错误**
老兵，掷雷兵等带有“技能持续时间”的职业技能持续时间似乎翻倍

**如何重现**
重现这个错误的步骤:
1. 打开游戏
2. 开老兵，测试模式，开始
3. 开警戒
4. 出现错误（设定时间到了仍处于警戒状态，2倍设定时间后结束警戒）

**截图**
如果需要，请添加屏幕截图以帮助解释您的问题。

**日志**
[LogOutput.log](https://github.com/KARPED1EM/TownOfNext/files/13804254/LogOutput.log)

**Comment by Slok7565** [comment]
版本是301，在测试的时候无意间发现的，后面下载301的dll也有这个问题

**Comment by Sand-and-Beans** [comment]
> 版本是301，在测试的时候无意间发现的，后面下载301的dll也有这个问题

这个不知道为啥，现在我给改成不用GetTimeStamp而是直接搞个计时器了
