### ISSUE TITLE
Gamemode Editor

### ISSUE THREAD

**Issue by borjita2019** [KARPED1EM/TownOfNext#62]
kinda a tohtor thing.

you can enable ffa or teams, add how many teams you have, you can configure what one team can do and what the other cant (lets say red team can kill blue team, but have LIMITED VISION and blue team can protect alive people on their team when they die. one team could spawn dead if the host decides it.), choose when the game will end (when everyone is a specific team color, when specific team is all dead.), enable team swapping (instead of killing them, swap their team to the killers team, tohtor manages to do it and plays a angel guardian shield anim.). ffa is just teams but every player has an individual team.
you can also name teams if its possible to do that in au mod, and make it display name for team (or just choose a color for the team,  also one team can spawn in random place by setting)

possible gamemodes with this are:
Hide and Seek (because TOHE isnt compatible with vanilla h&s yet)
FFA Team Swap
Team Swap
FFA Royale
Team Royale
Infection
Protect the King (every crewmate is dead, except for killers, king can vent but killers cant, crewmates can protect king)

i know this would take way too long, but it would be super fun to make gamemodes where everyone can enjoy

**Comment by borjita2019** [comment]
just for adding, an option to end the game when certain time has passed (time is on their name)

**Comment by KARPED1EM** [comment]
well, we don't plan to make a specific game mode yet.
it's too hard for ONE developer (I mean myself)

**Comment by KARPED1EM** [comment]
sorry to disappoint you

**Comment by borjita2019** [comment]
no worries, it was just if u wanted
