### ISSUE TITLE
Time doesn't end when voting hits 0

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfNext#96]
![image](https://user-images.githubusercontent.com/107776037/231567719-fbce10d7-f988-426e-8933-a89efb7cd8ef.png)
![image](https://user-images.githubusercontent.com/107776037/231567792-9e82f2ae-73ef-40f2-b97d-e683d10df771.png)

**Comment by chillultimated** [comment]
(я вижу тут русский) это не баг, это просто хост выходит из амонг аса и поэтому голосование не может закончится, если же хост ты и ты никуда не выходил то тогда да, это баг (к примеру хост может открыть режим приложения в окне на телефоне и сидеть в телеграме, а голосование в этот момент не сможет закончится)

**Comment by mogekonik1** [comment]
Это баг, ибо я всё время был в Among Us.

**Comment by mogekonik1** [comment]
> (я вижу тут русский) это не баг, это просто хост выходит из амонг аса и поэтому голосование не может закончится, если же хост ты и ты никуда не выходил то тогда да, это баг (к примеру хост может открыть режим приложения в окне на телефоне и сидеть в телеграме, а голосование в этот момент не сможет закончится)
(I see Russian here) this is not a bug, it's just the host leaving among asa and therefore the voting cannot end, if the host is you and you didn't go anywhere, then yes, this is a bug (for example, the host can open the application mode in the window on phone and sit in the telegram, and the voting at this moment will not be able to end)

**Comment by Gurge44** [comment]
This is a bug in vanilla TOH and it also happens when the Host is still in the game.

**Comment by KARPED1EM** [comment]
probably fixed in latest version of toh
